version: ~> 1.0
language: c
arch: amd64
os: linux
dist: focal
env:
  global:
   # Encrypted COVERITY_SCAN_TOKEN
   - secure: "MrREcPFffZzyQTpgk9AHDQm/Q+SNNuuZ5WFlp0ouQIHA6D5MGuDKh7A2EyoviGrJRxbkJD5ad4KKjJJ91jq10eRtABGVH7hndMcswogqPJqDDe0WBIIktoWVtoRnO9BqqB0/D7VLwkCv1GPcAKecDiyvfwaO8TLPZ2ETjvSbJOc="
jobs:
  include:
  - name: "Coverity"
    env:
    - CONFIGURE_OPTIONS=""
    - TARGET="coverity"
    compiler: clang
    group: edge
    addons:
      coverity_scan:
        project:
          name: "libyal/libcerror"
          description: "Build submitted via Travis CI"
        notification_email: joachim.metz@gmail.com
        build_command_prepend: "./synclibs.sh && ./autogen.sh && ./configure"
        build_command: "make -j4"
        branch_pattern: master
  - name: "Linux with gcc on ppc64le"
    env:
    - CONFIGURE_OPTIONS=""
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc"
    arch: ppc64le
    compiler: gcc
    group: edge
  - name: "Linux with gcc on s390x"
    env:
    - CONFIGURE_OPTIONS=""
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc"
    arch: s390x
    compiler: gcc
    group: edge
before_install:
- if test ${TARGET} != "coverity"; then .travis/before_install.sh; fi
- if test ${TARGET} = "coverity"; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi
install:
- if test ${TARGET} != "coverity" && test -x "synctestdata.sh"; then ./synctestdata.sh; fi
script:
- if test ${TARGET} != "coverity"; then export PATH=$(echo $PATH | tr ":" "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s/::/:/g"); tests/build.sh ${CONFIGURE_OPTIONS}; fi
