# Test build of library on Ubuntu Docker image
name: test_build_ubuntu
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ['ppc64le', 's390x']
    container:
      image: ${{ matrix.architecture }}/ubuntu:latest
    steps:
    - name: Set up container
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update -q
        apt-get install -y libterm-readline-gnu-perl locales software-properties-common
        locale-gen en_US.UTF-8
        ln -f -s /usr/share/zoneinfo/UTC /etc/localtime
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get -y install autoconf automake autopoint build-essential git libtool pkg-config
    - name: Download test data
      run: |
        if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
    - name: Build
      run: |
        tests/build.sh
    - name: Run tests
      run: |
        tests/runtests.sh
