# Test build of library on Ubuntu
name: test_build_ubuntu
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: ['x86', 'x64']
        compiler: [clang, gcc]
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get -y install autoconf automake autopoint build-essential git libtool pkg-config
    - name: Download test data
      run: |
        if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
    - name: Prepare build
      run: |
        ./synclibs.sh --use-head
        ./autogen.sh
    - name: Build
      env:
        CC: ${{ matrix.compiler }}
      run: |
        ./configure
        make > /dev/null
    - name: Run tests
      run: |
        .github/runtests.sh
